# Generated by Django 5.2 on 2025-04-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tumanow_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deviverer',
            new_name='deliverer',
        ),
    ]
