# Generated by Django 5.2 on 2025-04-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tumanow_app', '0004_alter_vendor_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_name', to='Tumanow_app.restaurant'),
        ),
    ]
